apiVersion: apps/v1
kind: Deployment
metadata:
  name: bolrea-malrea-backend
  labels:
    app: bolrea-malrea-backend
spec:
  revisionHistoryLimit: 3
  replicas: 1
  selector:
    matchLabels:
      app: bolrea-malrea-backend
  template:
    metadata:
      labels:
        app: bolrea-malrea-backend
    spec:
      serviceAccountName: bolrea-backend-sa
      containers:
        - name: backend
          image: 416963226971.dkr.ecr.ap-northeast-2.amazonaws.com/bolrea-malrea-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: bolrea-backend-config
            - secretRef:
                name: bolrea-backend-secret
