apiVersion: v1
kind: ConfigMap
metadata:
  name: bolrea-backend-config
data:
  ENV: development
  SQL_ECHO: "true"
  JWT_SECRET_ARN: "arn:aws:secretsmanager:ap-northeast-2:416963226971:secret:movie-dev/jwt-secret-Cnoe9I"
